// ──────────────────────────────────────────────────────────────
// Centralized profile options for courses, branches & skills
// Used by Student, Alumni, and Teacher profile setup forms
// ──────────────────────────────────────────────────────────────

// ── Educational Courses ─────────────────────────────────────
export const courseOptions = [
  // Diploma
  "Diploma in Engineering",
  "Diploma in Pharmacy",
  "Diploma in Computer Science",
  "Diploma in Electrical Engineering",
  "Diploma in Mechanical Engineering",
  "Diploma in Civil Engineering",
  "Diploma in Electronics & Telecommunication",

  // Undergraduate
  "B.Tech (Bachelor of Technology)",
  "B.E. (Bachelor of Engineering)",
  "B.Sc (Bachelor of Science)",
  "B.Sc (IT)",
  "B.Sc (Computer Science)",
  "BCA (Bachelor of Computer Applications)",
  "BBA (Bachelor of Business Administration)",
  "B.Com (Bachelor of Commerce)",
  "B.Arch (Bachelor of Architecture)",
  "B.Pharm (Bachelor of Pharmacy)",
  "B.Des (Bachelor of Design)",

  // Postgraduate
  "M.Tech (Master of Technology)",
  "M.E. (Master of Engineering)",
  "M.Sc (Master of Science)",
  "M.Sc (IT)",
  "M.Sc (Computer Science)",
  "MCA (Master of Computer Applications)",
  "MBA (Master of Business Administration)",
  "M.Com (Master of Commerce)",
  "M.Arch (Master of Architecture)",
  "M.Pharm (Master of Pharmacy)",
  "M.Des (Master of Design)",

  // Doctoral
  "Ph.D. (Doctor of Philosophy)",
  "D.Sc (Doctor of Science)",

  // Certifications / Others
  "PG Diploma",
  "Integrated B.Tech + M.Tech",
  "Other",
];

// ── Departments / Branches ──────────────────────────────────
export const departmentOptions = [
  // Computer & IT
  "Computer Science and Engineering",
  "Computer Science and Engineering (AI & ML)",
  "Computer Science and Engineering (Data Science)",
  "Computer Science and Engineering (Cyber Security)",
  "Computer Science and Engineering (IoT)",
  "Information Technology",
  "Artificial Intelligence and Data Science",
  "Artificial Intelligence and Machine Learning",
  "Data Science and Engineering",

  // Electronics & Communication
  "Electronics and Telecommunication Engineering",
  "Electronics and Communication Engineering",
  "Electronics Engineering",
  "Electronics and Instrumentation Engineering",
  "Instrumentation and Control Engineering",

  // Electrical
  "Electrical Engineering",
  "Electrical and Electronics Engineering",

  // Mechanical & Production
  "Mechanical Engineering",
  "Automobile Engineering",
  "Production Engineering",
  "Industrial Engineering",
  "Manufacturing Engineering",
  "Mechatronics Engineering",
  "Robotics and Automation",

  // Civil & Architecture
  "Civil Engineering",
  "Structural Engineering",
  "Environmental Engineering",
  "Architecture",

  // Chemical & Bio
  "Chemical Engineering",
  "Biotechnology Engineering",
  "Biochemical Engineering",
  "Biomedical Engineering",
  "Food Technology",
  "Pharmaceutical Engineering",

  // Other Engineering
  "Aerospace Engineering",
  "Mining Engineering",
  "Textile Engineering",
  "Agricultural Engineering",
  "Marine Engineering",
  "Petroleum Engineering",
  "Metallurgical Engineering",

  // Science & Commerce
  "Physics",
  "Chemistry",
  "Mathematics",
  "Commerce",
  "Management Studies",

  // Others
  "Other",
];

// ── Skills (categorized for display) ────────────────────────
export const skillCategories = {
  "Programming Languages": [
    "C",
    "C++",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "R",
    "MATLAB",
    "Scala",
    "Perl",
    "Dart",
    "C#",
    "Objective-C",
    "Shell Scripting",
    "SQL",
    "Assembly Language",
  ],
  "Web Development": [
    "HTML/CSS",
    "React",
    "Angular",
    "Vue.js",
    "Next.js",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Spring Boot",
    "ASP.NET",
    "Ruby on Rails",
    "Laravel",
    "Svelte",
    "Tailwind CSS",
    "Bootstrap",
    "jQuery",
    "WordPress",
    "REST APIs",
    "GraphQL",
    "WebSockets",
    "Full Stack Development",
  ],
  "Mobile Development": [
    "React Native",
    "Flutter",
    "Android Development",
    "iOS Development",
    "Xamarin",
    "Ionic",
    "SwiftUI",
    "Jetpack Compose",
  ],
  "Data Science & AI": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Data Science",
    "Data Analytics",
    "Data Visualization",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "Pandas",
    "NumPy",
    "OpenCV",
    "Generative AI",
    "Large Language Models (LLM)",
    "Reinforcement Learning",
    "Statistical Modeling",
    "Big Data Analytics",
    "Power BI",
    "Tableau",
    "Apache Spark",
  ],
  "Cloud & DevOps": [
    "AWS",
    "Azure",
    "Google Cloud Platform (GCP)",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "Linux Administration",
    "Nginx",
    "Apache",
    "Cloud Computing",
    "DevOps",
    "Serverless Architecture",
    "Microservices",
  ],
  "Databases": [
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Firebase",
    "Oracle Database",
    "SQL Server",
    "Cassandra",
    "DynamoDB",
    "Neo4j",
    "Elasticsearch",
    "SQLite",
  ],
  "Cyber Security": [
    "Cyber Security",
    "Ethical Hacking",
    "Penetration Testing",
    "Network Security",
    "Cryptography",
    "SOC Analysis",
    "SIEM Tools",
    "Vulnerability Assessment",
    "Digital Forensics",
    "OWASP",
  ],
  "Design & Multimedia": [
    "UI/UX Design",
    "Figma",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe Premiere Pro",
    "Blender",
    "Canva",
    "3D Modeling",
    "Video Editing",
    "Graphic Design",
    "Motion Graphics",
  ],
  "Emerging Technologies": [
    "Blockchain",
    "Internet of Things (IoT)",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Edge Computing",
    "Quantum Computing",
    "5G Technology",
    "Robotics",
    "Embedded Systems",
    "3D Printing",
  ],
  "Engineering Core": [
    "AutoCAD",
    "SolidWorks",
    "CATIA",
    "ANSYS",
    "MATLAB Simulink",
    "PLC Programming",
    "VLSI Design",
    "PCB Design",
    "Signal Processing",
    "Control Systems",
    "Thermodynamics",
    "Fluid Mechanics",
    "Structural Analysis",
    "Power Systems",
    "Electric Circuits",
  ],
  "Soft Skills & Management": [
    "Communication Skills",
    "Leadership",
    "Team Management",
    "Project Management",
    "Agile/Scrum",
    "Public Speaking",
    "Technical Writing",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Research Methodology",
    "Entrepreneurship",
  ],
  "Testing & QA": [
    "Manual Testing",
    "Automation Testing",
    "Selenium",
    "JUnit",
    "Cypress",
    "Jest",
    "Postman",
    "API Testing",
    "Performance Testing",
    "Load Testing",
  ],
  "Other Tools & Platforms": [
    "Git/GitHub",
    "Jira",
    "Confluence",
    "Slack",
    "VS Code",
    "IntelliJ IDEA",
    "Jupyter Notebook",
    "Google Colab",
    "SAP",
    "Salesforce",
    "ServiceNow",
  ],
};

// Flat list of all skills (for backward compatibility)
export const skillOptions = Object.values(skillCategories).flat();

// ── Teacher Specializations ─────────────────────────────────
export const specializationOptions = [
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Science",
  "Data Analytics",
  "Big Data",
  "Web Development",
  "Mobile App Development",
  "Software Engineering",
  "Cloud Computing",
  "Cyber Security",
  "Network Security",
  "Cryptography",
  "Embedded Systems",
  "Internet of Things (IoT)",
  "Blockchain Technology",
  "Robotics & Automation",
  "VLSI Design",
  "Signal Processing",
  "Communication Systems",
  "Digital Electronics",
  "Power Systems",
  "Control Systems",
  "Database Management",
  "Data Structures & Algorithms",
  "Operating Systems",
  "Computer Networks",
  "Compiler Design",
  "Theory of Computation",
  "Discrete Mathematics",
  "Numerical Methods",
  "Structural Engineering",
  "Geotechnical Engineering",
  "Transportation Engineering",
  "Water Resources Engineering",
  "Environmental Engineering",
  "Thermodynamics",
  "Heat Transfer",
  "Fluid Mechanics",
  "Manufacturing Processes",
  "CAD/CAM",
  "Automobile Engineering",
  "Nanotechnology",
  "Biotechnology",
  "Biomedical Engineering",
  "Renewable Energy",
  "Project Management",
  "Research Methodology",
  "Engineering Mathematics",
  "Engineering Physics",
  "Engineering Chemistry",
  "Other",
];
